### ISSUE TITLE
Package acceptance validation error

### ISSUE THREAD

**Issue by MarshallOfSound** [felixrieseberg/electron-windows-store#50] opened 2016-11-13 15:39 UTC
Hey @felixrieseberg 

I tried to submit my converted Electron application to the windows store and after jumping through too many hoops to count 😆 I ran into this glorious message on the Windows Store submission page.

> Package acceptance validation error: You don't have permissions to specify the following namespaces in the appx manifest file of the package GPMDP.appx: http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities

And that URL that is provided 404's....  Do you have any idea what's going on here?

**Comment by MarshallOfSound** [comment] 2016-11-13 15:42
Looks to be because of this line in the `appmanifest.xml`

https://github.com/felixrieseberg/electron-windows-store/blob/master/template/appxmanifest.xml#L23

Is this required?

**Comment by black-snow** [comment] 2016-12-01 13:52
@felixrieseberg Hey there. Anniversary has been around for a while so I wanted to push my app to the store.
Sadly this is what happens:

* Complaint about `PublisherDisplayName` being `Reserved`
* Complaint about `http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`

And also `Your developer account doesn’t have permission to submit apps converted with the Desktop Bridge at this time.` - but I guess I'll just have to fill out that form.

Kinda dupe of https://github.com/felixrieseberg/electron-windows-store/issues/17

**Comment by MarshallOfSound** [comment] 2016-12-01 13:57
@black-snow I was contacted  by a Microsoft rep about getting my developer account authorized to use the fields that are currently "reserved".  If you fill out the form you might get contacted 👍

**Comment by black-snow** [comment] 2016-12-01 14:25
@MarshallOfSound thanks. Let's see what happens next.

@felixrieseberg Is there anything we can do to improve this process? Maybe, for now, we should add some lines to the docs pointing to https://developer.microsoft.com/de-de/windows/projects/campaigns/desktop-bridge ? Do you work @MS? Any insights on when official support lands? (feels like a closed beta ;))

**Comment by felixrieseberg** [comment] 2016-12-03 10:13
I *used* to work at Microsoft (and during that time I built this thing). The added verification steps are more to ensure that developers are committed and worth the validation. Win32 apps (and all Electron apps) have full system access, meaning that the usual appx boundaries don't exist.

You can't build a UWP/appx package that runs `format c:`, but you can totally do that from an Electron app - which is why the added steps are there. Getting into the program shouldn't be too hard though, Microsoft usually <3 developers.

**Comment by felixrieseberg** [comment] 2016-12-03 10:15
I added a warning to the readme, so I'm closing this for now 👍

**Closed by felixrieseberg** 2016-12-03 10:15 UTC
